services:
  postgres:
    image: postgres:16-alpine
    container_name: notification-service-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: notification-service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file: .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: notification-service-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_ALIAS=notification-service-redis
      - RI_REDIS_PASSWORD=${REDIS_PASSWORD}

  ocr-provider:
    build:
      context: ./OcrProviderService
    container_name: ocr-provider
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file: ./OcrProviderService/.env
    environment:
      - REDIS_HOST=redis
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      redis:
        condition: service_healthy

  ocr-consumer:
    build:
      context: ./OcrConsumerService
    container_name: ocr-consumer
    ports:
      - "8001:8001"
    restart: unless-stopped
    env_file: ./OcrConsumerService/.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy

  notification-backend:
    build:
      context: ./NotificationService.Backend
    container_name: notification-service-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file: ./NotificationService.Backend/.env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  notification-frontend:
    build:
      context: ./NotificationService.Frontend
    container_name: notification-service-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - VITE_SOCKET_URL=http://localhost:8080
      - VITE_OCR_PROVIDER_URL=http://localhost:8000
    depends_on:
      - notification-backend

volumes:
  redis_data:
  redisinsight_data:
  postgres_data: